Added YouTubers to the index.html
KendallDoesCoding/youtubers-birthdays pull request #26
Opened 2023-04-01 11:58 UTC by PUJAmangale1221

2023-04-01 12:12 UTC, KendallDoesCoding requested changes
Please fix merge conflicts and then we will have to shift the order of the youtubers by catergory.

2023-04-02 05:57 UTC, PUJAmangale1221 commented
Done, Please have a look.

On Sat, 1 Apr 2023 at 17:42, Kendall ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please fix merge conflicts and then we will have to shift the order of the
> youtubers by catergory.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KendallDoesCoding/youtubers-birthdays/pull/26#pullrequestreview-1367853839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZJEWKSZGJT5CQH5Z7GJBRTW7ALUNANCNFSM6AAAAAAWPSYNBQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-04-02 06:29 UTC, KendallDoesCoding requested changes

2023-04-02 06:29 UTC, KendallDoesCoding commented on index.html
> +					<td><a href="https://youtube.com/@tomrworks">Timeworks</a></td>
```suggestion
					<td><a href="https://youtube.com/@timeworks">Timeworks</a></td>
```

2023-04-02 10:54 UTC, PUJAmangale1221 commented
What should I do?

On Sun, 2 Apr 2023, 11:59 am Kendall, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/KendallDoesCoding/youtubers-birthdays/pull/26#discussion_r1155247847>
> :
>
> >  				
> +				<tr>
> +					<td>Vlogs</td>
> +					<td><a ***@***.***">Chris Ivan</a></td>
> +					<td>Feburary 12, 1996</td>
> +					<td>600 million</td>
> +				</tr>
> +        <tr>
> +					<td>The YouTube Philanthropist</td>
> +					<td><a ***@***.***">MrBeast</a></td>
> +					<td> 7 May, 1998
> +					<td>20.9 billion</td>
> +				</tr>
> +				<tr>
> +					<td>Short Films</td>
> +					<td><a ***@***.***">Timeworks</a></td>
>
> ⬇️ Suggested change
>
> -					<td><a ***@***.***">Timeworks</a></td>
> +					<td><a ***@***.***">Timeworks</a></td>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KendallDoesCoding/youtubers-birthdays/pull/26#pullrequestreview-1368025967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZJEWKSNBAQ37XI3FVHUMI3W7EMD3ANCNFSM6AAAAAAWPSYNBQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-04-02 11:44 UTC, KendallDoesCoding approved these changes

2023-04-02 11:44 UTC, merged

2023-04-02 11:44 UTC, KendallDoesCoding commented
Thanks for your contribution @PUJAmangale1221.